services:
  - type: web
    name: assignment-2-ml-app
    env: python
    buildCommand: pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt || pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 2 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
